Repository DayoookE/dayoook-e-client, pull requests merged in 2024-12, with the labels that each got.

#13 Design/#5: 튜터 리스트 페이지
  package-lock.json
  package.json
  src/assets/ModalComponent/ic_dayook.svg
  src/assets/ModalComponent/ic_next.svg
  src/assets/ModalComponent/ic_prev.svg
  src/assets/ModalComponent/ic_x.svg
  src/assets/ModalComponent/index.js
  src/assets/TutorPage/ic_search.svg
  src/assets/TutorPage/ic_x.svg
  src/assets/TutorPage/index.js
  src/assets/face/img_face1.svg
  src/assets/face/img_face2.svg
  src/assets/face/img_face3.svg
  src/assets/face/img_face4.svg
  src/assets/face/index.js
  src/assets/icon/ic_dot.svg
  src/assets/icon/ic_star.svg
  src/assets/icon/index.js
  src/components/ModalComponent/ModalComponent.jsx
  src/components/ModalComponent/ModalComponent.style.js
  src/components/ModalComponent/RecommendModalItem/RecommendModalItem.jsx
  src/pages/Main/Main.jsx
  src/pages/Main/Main.style.js
  src/pages/Tutor/Tutor.jsx
  src/pages/Tutor/Tutor.style.js
  src/pages/Tutor/TutorList/TutorList.jsx
  src/pages/Tutor/TutorList/TutorList.style.js
  src/pages/Tutor/TutorMenu/TutorMenu.jsx
  src/pages/Tutor/TutorMenu/TutorMenu.style.js
  src/pages/Tutor/TutorSelect/TutorSelect.jsx
  src/pages/Tutor/TutorSelect/TutorSelect.style.js
  src/pages/Tutor/TutorSummary/TutorSummary.jsx
  src/pages/Tutor/TutorSummary/TutorSummary.style.js
  src/pages/Tutor/index.js
Labels: 🎀 design

#14 Design/#6: 동화 페이지
  src/App.css
  src/assets/FairyList/ic_heart.svg
  src/assets/FairyList/ic_heart_white.svg
  src/assets/FairyList/img_byeoljubujeon.svg
  src/assets/FairyList/img_fairy.svg
  src/assets/FairyList/img_gyeonwoo.svg
  src/assets/FairyList/img_heungbu.svg
  src/assets/FairyList/img_simcheong.svg
  src/assets/FairyList/index.js
  src/assets/MenuBar/ic_alarm_white.svg
  src/assets/MenuBar/ic_dropdown_white.svg
  src/assets/MenuBar/ic_lang_white.svg
  src/assets/MenuBar/index.js
  src/assets/Study/ic_fairytale.svg
  src/assets/Study/ic_game.svg
  src/assets/Study/ic_heart.svg
  src/assets/Study/ic_point.svg
  src/assets/Study/ic_prev.svg
  src/assets/Study/ic_read.svg
  src/assets/Study/ic_search.svg
  src/assets/Study/ic_shake.svg
  src/assets/Study/ic_talk.svg
  src/assets/Study/ic_title.svg
  src/assets/Study/ic_translation.svg
  src/assets/Study/img_book_content.svg
  src/assets/Study/img_china.svg
  src/assets/Study/img_korea.svg
  src/assets/Study/img_vietnam.svg
  src/assets/Study/index.js
  src/components/MenuBar/Alarm/Alarm.jsx
  src/components/MenuBar/Alarm/Alarm.style.js
  src/components/MenuBar/Lang/Lang.jsx
  src/components/MenuBar/MenuBar.jsx
  src/components/MenuBar/Profile/Profile.jsx
  src/components/MenuBar/Profile/Profile.style.js
  src/pages/Study/FairyList/FairyList.jsx
  src/pages/Study/FairyList/FairyList.style.js
  src/pages/Study/FairyRead/FairyRead.jsx
  src/pages/Study/FairyRead/FairyRead.style.js
  src/pages/Study/FairyRead/FairyReadContent/FairyReadContent.jsx
  src/pages/Study/FairyRead/FairyReadContent/FairyReadContent.style.js
  src/pages/Study/Study.jsx
  src/pages/Study/Study.style.js
  src/pages/Study/StudyBottom/SetFontSize/SetFontSize.jsx
  src/pages/Study/StudyBottom/SetFontSize/SetFontSize.style.js
  src/pages/Study/StudyBottom/StudyBottom.jsx
  src/pages/Study/StudyBottom/StudyBottom.style.js
  src/pages/Study/StudyContent/StudyContent.jsx
  src/pages/Study/StudyContent/StudyContent.style.js
  src/pages/Study/StudyContent/StudyOption/StudyOption.jsx
  src/pages/Study/StudyContent/StudyOption/StudyOption.style.js
Labels: 🎀 design

#15 Design/#11: 마이페이지
  src/assets/Mypage/ic_dashboard_green.svg
  src/assets/Mypage/ic_enter.svg
  src/assets/Mypage/ic_grade.svg
  src/assets/Mypage/ic_myimg.svg
  src/assets/Mypage/ic_mypage_white.svg
  src/assets/Mypage/ic_next.svg
  src/assets/Mypage/ic_prev.svg
  src/assets/Mypage/ic_set_info.svg
  src/assets/Mypage/ic_tutor.svg
  src/assets/Mypage/img_graph_face.svg
  src/assets/Mypage/img_profile_background.svg
  src/assets/Mypage/index.js
  src/pages/Mypage/MyCourse/MyCourse.jsx
  src/pages/Mypage/MyCourse/MyCourse.style.js
  src/pages/Mypage/MyInfo/MyInfo.jsx
  src/pages/Mypage/MyInfo/MyInfo.style.js
  src/pages/Mypage/Mypage.jsx
  src/pages/Mypage/Mypage.style.js
  src/pages/Mypage/MypageGraph/MypageGraph.jsx
  src/pages/Mypage/MypageGraph/MypageGraph.style.js
  src/pages/Mypage/Schedule/Schedule.jsx
  src/pages/Mypage/Schedule/Schedule.style.js
  src/pages/Mypage/Statistics/Statistics.jsx
  src/pages/Mypage/Statistics/Statistics.style.js
  src/pages/Mypage/index.js
Labels: ✨ feature, 🎀 design

#16 Design/#12: 복습 페이지
  src/App.js
  src/assets/Mypage/Review/ic_award.svg
  src/assets/Mypage/Review/ic_chat.svg
  src/assets/Mypage/Review/ic_prev_page.svg
  src/assets/Mypage/Review/ic_record.svg
  src/assets/Mypage/Review/ic_review.svg
  src/assets/Mypage/Review/ic_send.svg
  src/assets/Mypage/Review/ic_speaker.svg
  src/assets/Mypage/Review/ic_stop.svg
  src/assets/Mypage/Review/img_bot.svg
  src/assets/Mypage/Review/img_cheer_background.svg
  src/assets/Mypage/Review/index.js
  src/assets/NavBar/ic_mypage_green.svg
  src/assets/NavBar/ic_mypage_white.svg
  src/assets/NavBar/ic_study_green.svg
  src/assets/NavBar/ic_study_white.svg
  src/assets/NavBar/index.js
  src/components/NavBar/NavBar.jsx
  src/pages/Review/Chat/Chat.jsx
  src/pages/Review/Chat/Chat.style.js
  src/pages/Review/Chat/ChatList/ChatList.jsx
  src/pages/Review/Chat/ChatList/ChatList.style.js
  src/pages/Review/Chat/Input/Input.jsx
  src/pages/Review/Chat/Input/Input.style.js
  src/pages/Review/Content/Content.jsx
  src/pages/Review/Content/Content.style.js
  src/pages/Review/Review.jsx
  src/pages/Review/Review.style.js
  src/pages/Review/ReviewContent/ReviewContent.jsx
  src/pages/Review/ReviewContent/ReviewContent.style.js
  src/pages/Review/ReviewInfo/ReviewInfo.jsx
  src/pages/Review/ReviewInfo/ReviewInfo.style.js
  src/pages/Review/ReviewMenu/ReviewMenu.jsx
  src/pages/Review/ReviewMenu/ReviewMenu.style.js
  src/pages/index.js
Labels: ✨ feature, 🎀 design

#20 Design/#17: 튜터 마이페이지
  src/App.js
  src/assets/Mypage/Tutor/ic_class_enter.svg
  src/assets/Mypage/Tutor/ic_class_exit.svg
  src/assets/Mypage/Tutor/index.js
  src/assets/NavBar/ic_tutor_mypage.svg
  src/assets/NavBar/index.js
  src/assets/level/ic_flower.svg
  src/assets/level/ic_fruit.svg
  src/assets/level/ic_leaf.svg
  src/assets/level/index.js
  src/components/NavBar/NavBar.jsx
  src/components/NavBar/NavBar.style.js
  src/pages/Mypage/MyInfo/MyInfo.jsx
  src/pages/Mypage/MyInfo/MyInfo.style.js
  src/pages/Mypage/MypageGraph/MypageGraph.jsx
  src/pages/Mypage/TutorMypage/TuteeApplication/TuteeApplication.jsx
  src/pages/Mypage/TutorMypage/TuteeApplication/TuteeApplication.style.js
  src/pages/Mypage/TutorMypage/TuteeList/TuteeList.jsx
  src/pages/Mypage/TutorMypage/TuteeList/TuteeList.style.js
  src/pages/Mypage/TutorMypage/TutorMypage.jsx
  src/pages/Mypage/TutorMypage/TutorMypage.style.js
Labels: 🎀 design

#21 feat/#19: 로그인 API 연동
  .gitignore
  .idea/inspectionProfiles/Project_Default.xml
  package-lock.json
  package.json
  src/App.js
  src/pages/Login/Login.jsx
  src/pages/Login/Login.style.js
Labels: ✨ feature

#25 feat/#22: buildspec.yml 수정
  buildspec.yml
Labels: ✨ feature

#26 fix/#18: 페이지 구글 번역 에러
  src/components/MenuBar/MenuBar.jsx
Labels: 🚑 fix

#27 Feat/#22: 홈화면 api 연결
  src/components/MenuBar/MenuBar.jsx
  src/components/MenuBar/Profile/Profile.jsx
  src/components/MenuBar/Profile/ProfilePopup/ProfilePopup.jsx
  src/pages/Main/Assistant/Assistant.jsx
  src/pages/Main/Info/Info.jsx
  src/pages/Main/Info/Info.style.js
  src/pages/Main/Main.jsx
Labels: ✨ feature

#30 feat/#28: 마이페이지 유저 정보 조회 api 연결
  src/App.js
  src/components/common/UserContext.js
  src/pages/Main/Main.jsx
  src/pages/Mypage/MyInfo/MyInfo.jsx
  src/pages/Mypage/Mypage.jsx
  src/pages/Mypage/MypageGraph/MypageGraph.jsx
Labels: ✨ feature

#31 fix: 충돌 해결
  src/pages/Main/Main.jsx
Labels: ✨ feature

#33 Feat/#32: 발음 피드백 API 연동
  src/assets/FairyList/ic_dayook.svg
  src/assets/FairyList/index.js
  src/pages/Study/FairyRead/FairyReadContent/FairyReadContent.jsx
  src/pages/Study/FairyRead/FeedbackModal/FeedbackModal.jsx
  src/pages/Study/FairyRead/FeedbackModal/FeedbackModal.style.js
Labels: ✨ feature, 🎀 design

#36 Fix/#35: 로그인 유무 에러 수정
  src/App.js
Labels: 🚑 fix

#41 Feat/#39: 복습 리스트 조회
  src/assets/Mypage/Review/ic_list_down.svg
  src/assets/Mypage/Review/ic_list_up.svg
  src/assets/Mypage/Review/index.js
  src/pages/Review/ReviewInfo/ReviewInfo.jsx
  src/pages/Review/ReviewInfo/ReviewInfo.style.js
Labels: ✨ feature, 🎀 design

#42 feat/#34 튜터 목록 페이지 API 연동
  src/components/ModalComponent/ModalComponent.jsx
  src/pages/Main/Main.jsx
  src/pages/Tutor/Tutor.jsx
  src/pages/Tutor/TutorList/TutorList.jsx
  src/pages/Tutor/TutorList/TutorList.style.js
Labels: ✨ feature

#40 Feat/#28: 마이페이지 api 연결
  package-lock.json
  package.json
  src/App.js
  src/components/common/MappingContext.jsx
  src/pages/Mypage/MyCourse/MyCourse.jsx
  src/pages/Mypage/MyInfo/MyInfo.jsx
  src/pages/Mypage/Schedule/Schedule.jsx
Labels: ✨ feature

#47 Feat/#37: 수강 신청 API 연동
  src/pages/Tutor/TutorApplyModal/TutorApplyModal.jsx
  src/pages/Tutor/TutorApplyModal/TutorApplyModal.style.js
  src/pages/Tutor/TutorList/TutorList.jsx
Labels: ✨ feature

#50 Feat/#48: 수강 승인 API 연동
  src/App.js
  src/assets/TutorPage/ic_check.svg
  src/assets/TutorPage/index.js
  src/pages/Mypage/MypageGraph/MypageGraph.jsx
  src/pages/Mypage/TutorMypage/TuteeApplication/TuteeApplication.jsx
  src/pages/Mypage/TutorMypage/TuteeApplication/TuteeApplication.style.js
Labels: ✨ feature

#51 feat/#49: 튜터 상세조회 api 연결
  src/pages/Tutor/Tutor.jsx
  src/pages/Tutor/TutorList/TutorList.jsx
  src/pages/Tutor/TutorSummary/TutorSummary.jsx
Labels: ✨ feature

#66 Feat/#46: 로그아웃 기능
  src/App.js
  src/components/NavBar/NavBar.jsx
  src/pages/Main/Main.jsx
Labels: ✨ feature

#67 Feat/#55: 튜터 카드 선택시 튜터 세부정보 제공
  src/pages/Tutor/Tutor.jsx
  src/pages/Tutor/TutorList/TutorList.jsx
  src/pages/Tutor/TutorList/TutorList.style.js
  src/pages/Tutor/TutorSummary/TutorSummary.jsx
  src/pages/Tutor/TutorSummary/TutorSummary.style.js
Labels: ✨ feature

#68 feat/#60 동화 세부기능 API 연결
  src/pages/Study/FairyList/FairyList.jsx
  src/pages/Study/FairyList/FairyList.style.js
  src/pages/Study/FairyRead/FairyRead.jsx
  src/pages/Study/FairyRead/FairyReadContent/FairyReadContent.jsx
  src/pages/Study/StudyContent/StudyContent.jsx
  src/pages/Study/StudyContent/StudyOption/StudyOption.jsx
Labels: ✨ feature

#69 Feat/#62: 튜터 신청시 가능 시간 선택
  src/pages/Tutor/TutorApplyModal/TutorApplyModal.jsx
  src/pages/Tutor/TutorApplyModal/TutorApplyModal.style.js
  src/pages/Tutor/TutorList/TutorList.jsx
  src/pages/Tutor/TutorSummary/TutorSummary.jsx
Labels: ✨ feature

#71 Feat/#70: 튜터 마이페이지 개선
  src/pages/Mypage/MyInfo/MyInfo.jsx
  src/pages/Mypage/TutorMypage/TuteeList/TuteeList.jsx
Labels: ✨ feature

#72 fix/#65: 패스워드 입력 공란 버그 해결
  src/pages/Login/Login.jsx
Labels: 🚑 fix

#75 Feat/#54: 강의 세부기능
  src/assets/Mypage/Tutor/ic_link.svg
  src/assets/Mypage/Tutor/index.js
  src/pages/Mypage/TutorMypage/TuteeList/TuteeList.jsx
  src/pages/Mypage/TutorMypage/TuteeList/TuteeList.style.js
Labels: ✨ feature

#77 feat/#58 튜터 필터링 기능 추가
  src/components/common/MappingContext.jsx
  src/pages/Tutor/TutorList/TutorList.jsx
  src/pages/Tutor/TutorMenu/TutorMenu.jsx
  src/pages/Tutor/TutorSelect/TutorSelect.jsx
Labels: ✨ feature

#79 Feat/#74: 수강 불가능한 사유 제공
  src/pages/Tutor/TutorApplyModal/TutorApplyModal.jsx
  src/pages/Tutor/TutorList/TutorList.jsx
  src/pages/Tutor/TutorSummary/TutorSummary.jsx
Labels: ✨ feature

#80 Feat/#61: 프로필 팝업 관련 링크 연결
  src/components/MenuBar/Alarm/Alarm.jsx
  src/components/MenuBar/MenuBar.jsx
  src/components/MenuBar/Profile/Profile.jsx
  src/components/MenuBar/Profile/ProfilePopup/ProfilePopup.jsx
Labels: ✨ feature

#81 Feat/#59: 페이지 번역 기능
  src/components/MenuBar/MenuBar.jsx
Labels: ✨ feature

#87 Design/#86: 폰트 및 이미지 크기 수정
  src/App.css
  src/assets/Study/ic_white_heart_big.svg
  src/assets/Study/index.js
  src/index.css
  src/pages/Study/StudyContent/StudyOption/StudyOption.jsx
  src/pages/Study/StudyContent/StudyOption/StudyOption.style.js
Labels: 🎀 design

#88 Fix/#83: 튜터 리스트 페이지에서도 추천 받을 수 있게 수정
  src/pages/Tutor/Tutor.jsx
  src/pages/Tutor/TutorList/TutorList.style.js
  src/pages/Tutor/TutorMenu/TutorMenu.jsx
Labels: 🚑 fix

#90 Feat/#84: 마이페이지 사용자 세부 정보 제공
  src/assets/Mypage/ic_point_new.svg
  src/assets/Mypage/index.js
  src/pages/Mypage/MyInfo/MyInfo.jsx
Labels: ✨ feature

#91 fix/#82: 메뉴바에 프로필 안 뜨는 경우 해결
  src/components/MenuBar/Profile/Profile.jsx
  src/pages/Mypage/MyInfo/MyInfo.jsx
Labels: 🚑 fix

#92 Feat/#56: 복습 업로드 API 연동
  package-lock.json
  package.json
  public/testContent.wav
  src/pages/Login/Login.jsx
  src/pages/Mypage/TutorMypage/TuteeList/TuteeList.jsx
Labels: ✨ feature
